version: '3.1'

services:
  db:
    image: mysql:8.0.26
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Iik100410*
      - MYSQL_DATABASE=bank
  lab2:
    image: ivonazoricic/bank
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3307
    ports:
      - "8080:8080"
    depends_on:
      - db


